
# **Company Check**



In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib

Using matplotlib backend: agg


In [3]:
cc=pd.read_csv("/content/drive/MyDrive/ass1/ASS2/Company_Data.csv")

In [4]:
cc.head()

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42   
1  11.22        111      48           16         260     83      Good   65   
2  10.06        113      35           10         269     80    Medium   59   
3   7.40        117     100            4         466     97    Medium   55   
4   4.15        141      64            3         340    128       Bad   38   

   Education Urban   US  
0         17   Yes  Yes  
1         10   Yes  Yes  
2         12   Yes  Yes  
3         14   Yes  Yes  
4         13   Yes   No

In [7]:
cc.columns

Index(['Sales', 'CompPrice', 'Income', 'Advertising', 'Population', 'Price',
       'ShelveLoc', 'Age', 'Education', 'Urban', 'US'],
      dtype='object')

In [8]:
cc.corr()

Sales  CompPrice    Income  Advertising  Population     Price  \
Sales        1.000000   0.064079  0.151951     0.269507    0.050471 -0.444951   
CompPrice    0.064079   1.000000 -0.080653    -0.024199   -0.094707  0.584848   
Income       0.151951  -0.080653  1.000000     0.058995   -0.007877 -0.056698   
Advertising  0.269507  -0.024199  0.058995     1.000000    0.265652  0.044537   
Population   0.050471  -0.094707 -0.007877     0.265652    1.000000 -0.012144   
Price       -0.444951   0.584848 -0.056698     0.044537   -0.012144  1.000000   
Age         -0.231815  -0.100239 -0.004670    -0.004557   -0.042663 -0.102177   
Education   -0.051955   0.025197 -0.056855    -0.033594   -0.106378  0.011747   

                  Age  Education  
Sales       -0.231815  -0.051955  
CompPrice   -0.100239   0.025197  
Income      -0.004670  -0.056855  
Advertising -0.004557  -0.033594  
Population  -0.042663  -0.106378  
Price       -0.102177   0.011747  
Age          1.000000   0.006488  
Education    0.006488   1.000000

In [10]:
cc.drop(['US','ShelveLoc','Urban','Education','Population'],inplace=True,axis=1)

In [11]:
X = cc.drop('Sales',axis=1)
y = cc['Sales']

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=101)

In [14]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled_train = scaler.fit_transform(X_train)

X_scaled_test = scaler.transform(X_test)

In [15]:
from sklearn.tree import DecisionTreeRegressor

In [16]:
dtree_reg = DecisionTreeRegressor()
dtree_reg.fit(X_scaled_train,y_train)
print(dtree_reg.feature_importances_)

[0.17052137 0.09872981 0.16062353 0.36592376 0.20420153]


In [17]:
from sklearn.ensemble import RandomForestRegressor

In [18]:
from sklearn.model_selection import GridSearchCV, KFold , RandomizedSearchCV

In [19]:
rfr = RandomForestRegressor()

In [20]:
import warnings
warnings.filterwarnings('ignore')

In [22]:
min_samples_split = [3,4,5,6,7,8]
max_depth = [3,4,5,6,7]
max_features = [None,3,4,5]
n_estimators = [90,100,125,150,200]
n_jobs =[-1]

param_grid = dict(n_estimators = n_estimators, n_jobs = n_jobs, min_samples_split = min_samples_split,max_depth = max_depth,max_features= max_features,)

grid = GridSearchCV(estimator = rfr,param_grid = param_grid,cv = KFold(n_splits=5,shuffle=True), verbose = 10)
grid_result = grid.fit(X_scaled_train,y_train)

Streaming output truncated to the last 5000 lines.
[CV 1/5; 101/600] START max_depth=3, max_features=5, min_samples_split=5, n_estimators=90, n_jobs=-1
[CV 1/5; 101/600] END max_depth=3, max_features=5, min_samples_split=5, n_estimators=90, n_jobs=-1;, score=0.308 total time=   0.3s
[CV 2/5; 101/600] START max_depth=3, max_features=5, min_samples_split=5, n_estimators=90, n_jobs=-1
[CV 2/5; 101/600] END max_depth=3, max_features=5, min_samples_split=5, n_estimators=90, n_jobs=-1;, score=0.331 total time=   0.3s
[CV 3/5; 101/600] START max_depth=3, max_features=5, min_samples_split=5, n_estimators=90, n_jobs=-1
[CV 3/5; 101/600] END max_depth=3, max_features=5, min_samples_split=5, n_estimators=90, n_jobs=-1;, score=0.273 total time=   0.3s
[CV 4/5; 101/600] START max_depth=3, max_features=5, min_samples_split=5, n_estimators=90, n_jobs=-1
[CV 4/5; 101/600] END max_depth=3, max_features=5, min_samples_split=5, n_estimators=90, n_jobs=-1;, score=0.294 total time=   0.3s
[CV 5/5; 101/600]

In [23]:
grid_result.best_params_

{'max_depth': 7,
 'max_features': 5,
 'min_samples_split': 8,
 'n_estimators': 90,
 'n_jobs': -1}

In [24]:
rfr = RandomForestRegressor(n_estimators=100,max_depth=7, max_features=5, min_samples_split=3,n_jobs=-1)

In [25]:
rfr.fit(X_scaled_train,y_train)

RandomForestRegressor(max_depth=7, max_features=5, min_samples_split=3,
                      n_jobs=-1)

In [26]:
rfr.score(X_scaled_test,y_test)

0.4349658784195325

In [27]:
prediction = rfr.predict(X_scaled_test)


In [28]:
from sklearn.metrics import mean_squared_error
rms = mean_squared_error(y_test, prediction, squared=True)

In [29]:
len(y_test)

132

In [30]:
(prediction[1] - y_test.iloc[1])

-0.08557363079217062

In [31]:
y_test.iloc[1]

8.67

In [32]:
def mean_squared_error(predict,actual):
    sum =0
    for i in range(len(predict)):
        sum = sum + (prediction[1] - y_test.iloc[1]) * (prediction[1] - y_test.iloc[1])
        
    return sum/len(predict)

In [33]:
ssr = mean_squared_error(prediction,y_test)

In [34]:
print(f"Sum of squared residual: {ssr}")

Sum of squared residual: 0.007322846286954759


**Fraud check**

In [36]:
fraud=pd.read_csv("/content/drive/MyDrive/ass1/ASS2/Fraud_check.csv")

In [37]:
fraud.head()

Undergrad Marital.Status  Taxable.Income  City.Population  Work.Experience  \
0        NO         Single           68833            50047               10   
1       YES       Divorced           33700           134075               18   
2        NO        Married           36925           160205               30   
3       YES         Single           50190           193264               15   
4        NO        Married           81002            27533               28   

  Urban  
0   YES  
1   YES  
2   YES  
3   YES  
4    NO

In [38]:
fraud['Taxable.Income'] =  ['Risky' if x<=30000 else 'Good' for x in fraud['Taxable.Income']]

In [ ]:
fraud.head()

In [39]:
fraud['Taxable.Income'].value_counts()

Good     476
Risky    124
Name: Taxable.Income, dtype: int64

In [40]:
fraud = pd.get_dummies(fraud,drop_first=True)

In [41]:
fraud.corr

<bound method DataFrame.corr of      City.Population  Work.Experience  Undergrad_YES  Marital.Status_Married  \
0              50047               10              0                       0   
1             134075               18              1                       0   
2             160205               30              0                       1   
3             193264               15              1                       0   
4              27533               28              0                       1   
..               ...              ...            ...                     ...   
595            39492                7              1                       0   
596            55369                2              1                       0   
597           154058                0              0                       0   
598           180083               17              1                       1   
599           158137               16              0                       0   

     Ma

In [42]:
plt.figure(figsize=(11,7))
sns.countplot(x='Taxable.Income_Risky',hue='Undergrad_YES',data=fraud,palette='Set1')

In [43]:
plt.figure(figsize=(11,7))
sns.countplot(x='Taxable.Income_Risky',hue='Marital.Status_Married',data=fraud,palette='Set1')

In [44]:
X = fraud.drop('Taxable.Income_Risky',axis=1)
y = fraud['Taxable.Income_Risky']

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=101)

In [46]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled_train = scaler.fit_transform(X_train)

X_scaled_test = scaler.transform(X_test)

In [47]:
from sklearn.ensemble import RandomForestClassifier

In [48]:
from sklearn.model_selection import GridSearchCV, KFold , RandomizedSearchCV

In [49]:
rfc = RandomForestClassifier()

In [53]:


min_samples_split = [3,4,5,6,7,8]
max_depth = [3,4,5,6,7]
max_features = [None,3,4,5]
n_estimators = [90,100,125,150,200]
n_jobs =[-1]

param_grid = dict(n_estimators = n_estimators, n_jobs = n_jobs, min_samples_split = min_samples_split,max_depth = max_depth,max_features= max_features,)

grid = GridSearchCV(estimator = rfr,param_grid = param_grid,cv = KFold(n_splits=5,shuffle=True), verbose = 10)
grid_result = grid.fit(X_scaled_train,y_train)

Streaming output truncated to the last 5000 lines.
[CV 1/5; 101/600] START max_depth=3, max_features=5, min_samples_split=5, n_estimators=90, n_jobs=-1
[CV 1/5; 101/600] END max_depth=3, max_features=5, min_samples_split=5, n_estimators=90, n_jobs=-1;, score=-0.044 total time=   0.3s
[CV 2/5; 101/600] START max_depth=3, max_features=5, min_samples_split=5, n_estimators=90, n_jobs=-1
[CV 2/5; 101/600] END max_depth=3, max_features=5, min_samples_split=5, n_estimators=90, n_jobs=-1;, score=-0.123 total time=   0.3s
[CV 3/5; 101/600] START max_depth=3, max_features=5, min_samples_split=5, n_estimators=90, n_jobs=-1
[CV 3/5; 101/600] END max_depth=3, max_features=5, min_samples_split=5, n_estimators=90, n_jobs=-1;, score=-0.021 total time=   0.3s
[CV 4/5; 101/600] START max_depth=3, max_features=5, min_samples_split=5, n_estimators=90, n_jobs=-1
[CV 4/5; 101/600] END max_depth=3, max_features=5, min_samples_split=5, n_estimators=90, n_jobs=-1;, score=-0.023 total time=   0.3s
[CV 5/5; 101/

In [54]:
grid_result.best_estimator_

RandomForestRegressor(max_depth=3, max_features=3, min_samples_split=8,
                      n_estimators=200, n_jobs=-1)

In [57]:
rfr = RandomForestRegressor(n_estimators=100,max_depth=7, max_features=5, min_samples_split=3,n_jobs=-1)

In [58]:
rfc.fit(X_scaled_train,y_train)

RandomForestClassifier()

In [59]:
print(rfc.feature_importances_)

[0.53522565 0.33572145 0.03329549 0.02920743 0.02874706 0.03780292]


In [60]:
X_train_new = X_scaled_train[:,[0,1,3]]
X_test_new = X_scaled_test[:,[0,1,3]]

In [61]:
rfc.fit(X_train_new,y_train)

RandomForestClassifier()

In [62]:
predict = rfc.predict(X_test_new)

In [63]:
from sklearn.metrics import classification_report,confusion_matrix

In [65]:
print(classification_report(y_test,predict))

print(confusion_matrix(y_test,predict))

              precision    recall  f1-score   support

           0       0.79      0.88      0.83       158
           1       0.17      0.10      0.13        40

    accuracy                           0.72       198
   macro avg       0.48      0.49      0.48       198
weighted avg       0.67      0.72      0.69       198

[[139  19]
 [ 36   4]]


In [66]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler()

In [67]:
X_train_res, y_train_res = ros.fit_resample(X_train_new, y_train)

In [68]:
rfc.fit(X_train_res,y_train_res)

RandomForestClassifier()

In [69]:
probs_y = rfc.predict_proba(X_test_new)

In [70]:
from sklearn.metrics import precision_recall_curve
precision, recall, thresholds = precision_recall_curve(y_test, probs_y[:, 1]) 

plt.title("Precision-Recall vs Threshold Chart")
plt.plot(thresholds, precision[: -1], "b--", label="Precision")
plt.plot(thresholds, recall[: -1], "r--", label="Recall")
plt.ylabel("Precision, Recall")
plt.xlabel("Threshold")
plt.legend(loc="lower left")

plt.ylim([0,1])

(0.0, 1.0)

In [71]:
model = probs_y[:,1]
model = [1 if x>=0.45 else 0 for x in model]


print(classification_report(y_test,model))

print(confusion_matrix(y_test,model))

              precision    recall  f1-score   support

           0       0.79      0.76      0.78       158
           1       0.19      0.23      0.21        40

    accuracy                           0.65       198
   macro avg       0.49      0.49      0.49       198
weighted avg       0.67      0.65      0.66       198

[[120  38]
 [ 31   9]]
