In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
import pandas as pd
import numpy as np



     |████████████████████████████████| 93 kB 1.3 MB/s 


In [21]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier



In [24]:
df =pd.read_csv("/content/drive/MyDrive/Assignment/pima-indians-diabetes.csv")

In [28]:
df.columns=['preg','plas','pres','skin','test','mass','pedi','age','class']

In [29]:
df

preg  plas  pres  skin  test  mass   pedi  age  class
0       1    85    66    29     0  26.6  0.351   31      0
1       8   183    64     0     0  23.3  0.672   32      1
2       1    89    66    23    94  28.1  0.167   21      0
3       0   137    40    35   168  43.1  2.288   33      1
4       5   116    74     0     0  25.6  0.201   30      0
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
762    10   101    76    48   180  32.9  0.171   63      0
763     2   122    70    27     0  36.8  0.340   27      0
764     5   121    72    23   112  26.2  0.245   30      0
765     1   126    60     0     0  30.1  0.349   47      1
766     1    93    70    31     0  30.4  0.315   23      0

[767 rows x 9 columns]

In [30]:
#Bagging
array=df.values
X=array[:,0:8]
Y=array[:,8]
seed=7
Kfold=KFold(n_splits=10)
cart=DecisionTreeClassifier()
num_trees=100
model=BaggingClassifier(base_estimator=cart,n_estimators=num_trees,random_state=seed)
results=cross_val_score(model,X,Y,cv=Kfold)



In [31]:
results

array([0.67532468, 0.87012987, 0.74025974, 0.64935065, 0.81818182,
       0.83116883, 0.84415584, 0.82894737, 0.67105263, 0.80263158])

In [32]:
print(results.mean())

0.7731203007518797


In [49]:
from sklearn.ensemble import RandomForestClassifier

In [50]:
X=array[:,0:8]
Y=array[:,8]
num_trees=100
max_featues=3
kfold=KFold(n_splits=10)
model=RandomForestClassifier(n_estimators=num_trees,max_features=max_featues)
result=cross_val_score(model,X,Y,cv=kfold)

In [51]:
result

array([0.67532468, 0.80519481, 0.74025974, 0.63636364, 0.83116883,
       0.79220779, 0.81818182, 0.86842105, 0.69736842, 0.78947368])

In [52]:
print(result.mean())

0.7653964456596036


In [56]:
#ADABOOST CLASSIFICATION
from sklearn.ensemble import AdaBoostClassifier
X=array[:,0:8]
Y=array[:,8]
num_trees=10
seed=7
kfold=KFold(n_splits=10)
model=AdaBoostClassifier(n_estimators=num_trees,random_state=seed)
results=cross_val_score(model,X,Y,cv=kfold)

In [59]:
results

array([0.7012987 , 0.79220779, 0.66233766, 0.64935065, 0.75324675,
       0.84415584, 0.77922078, 0.82894737, 0.72368421, 0.75      ])

In [60]:
results.mean()

0.748444976076555

In [62]:
#Stacking
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
X=array[:,0:8]
Y=array[:,8]
num_trees=10
kfold=KFold(n_splits=10)

#create submodels
estimators=[]
m1=LogisticRegression(max_iter=500)
estimators.append(('LOG',m1))
m2=DecisionTreeClassifier()
estimators.append(('DT',m2))
m3=SVC()
estimators.append(('SVM',m3))
#create ensemble
ensemble=VotingClassifier(estimators)
results=cross_val_score(ensemble,X,Y,cv=kfold)



In [63]:
results

array([0.66233766, 0.81818182, 0.72727273, 0.63636364, 0.77922078,
       0.80519481, 0.81818182, 0.86842105, 0.75      , 0.77631579])

In [65]:
results.mean()

0.764149008885851